apiVersion: v1
kind: Service
metadata:
  name: mongo2
  labels:
    name: mongo2
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo2
